[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "memory-game"
version = "0.1.0"
description = "메모리 게임"
dependencies = [
    "pygame",
]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["game"]